- name: Sales Demo Application Init
  hosts: bastion
  gather_facts: false
  tasks:
    - name: openShift sales-init
      args:
        warn: false
      command: oc start-build sales-init-pipeline -n devops-tools --wait
