- name: Sales Demo Application Stock Processor Service
  hosts: bastion
  gather_facts: false
  tasks:
    - name: openShift sales-stock-processor
      args:
        warn: false
      command: oc start-build sales-deploy-stock-processor-pipeline -n devops-tools --wait
