- name: Sales Demo Application Infra
  hosts: bastion
  gather_facts: false
  tasks:
    - name: openShift sales-infra
      args:
        warn: false
      command: oc start-build sales-infra-pipeline -n devops-tools --wait
