- name: Sales Demo Application Login
  hosts: bastion
  gather_facts: false
  tasks:
    - name: openShift login
      args:
        warn: false
#      command: oc login {{sales_demo_ocp_url}} --token={{sales_demo_ocp_token}}
       command: "oc login https://master.barcelona-e984.openshiftworkshop.com:443 --token=iIjjy-eIV1GHQlQISjkKWo6-WJsT7B1YB_q8ghp_s4E"
