- name: Sales Demo Application Login
  hosts: bastion
  gather_facts: false
  tasks:
    - name: openShift login
      args:
        warn: false
      command: oc login {{sales_demo_ocp_url}} --token={{sales_demo_ocp_token}}
