- name: Sales Demo Application Ticket Processor Service
  hosts: bastion
  gather_facts: false
  tasks:
    - name: openShift sales-ticket-processor
      args:
        warn: false
      command: oc start-build sales-deploy-ticket-processor-pipeline -n devops-tools -e TICKETING_SERVICE_VERSION={{project_version}} --wait
