- name: Sales Application Pre-reqs
  hosts: bastion
  gather_facts: false
  tasks:
    - name: openShift sales-prereqs
      args:
        warn: false
      command: oc start-build sales-prereqs-pipeline -n cicd-ocpadmin --wait
