- name: Slack Notifier
  hosts: bastion
  gather_facts: false
  tasks:
    - name: Send notification message via Slack
      slack:
        token: "{{ slack_token }}"
        msg: "[{{ project_version }}] @ {{ slack_msg }}"
        channel: '{{ slack_channel }}'

